// myPortfolio/src/components/Home.tsx
import imageName from "../assets/fotoProfilo.jpg";
import "./scss/Home.scss";
const Home = () => {
  return (
    <div className="home">
      <div className="home-img">
        <img src={imageName} alt="" />
      </div>
        <h2>
          Hi there, I'm <span className="V">Valerio</span>. A junior Web Developer passionate about <span className="C">coding</span> and digital design.
        </h2>
    </div>
  );
};

export default Home;

// my-app/src/app/Components/home/home.component.ts

  import { Component, OnInit, ElementRef } from '@angular/core';
  @Component({
    selector: 'app-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.scss']
  })
  export class HomeComponent implements OnInit{
    typedText: string = '';
    originalText: string = "Hi there i'm Valerio, a junior Web Developer passionate about coding and web Design.";
    aboutIndex: number = 0;
    currentIndex: number = 0;
    typingSpeed: number = 70 ;
    constructor(private elementRef: ElementRef) {}

    ngOnInit() {
      this.type();
    }

    type() :void{
      if (this.currentIndex < this.originalText.length) {
        this.typedText += this.originalText.charAt(this.currentIndex);
        this.currentIndex++;
        setTimeout(() => this.type(), this.typingSpeed);
    }
  }}

<div class="home" id="home" #sezione1>
<div class="cont">
    <div class="col-lg-8" id="typewriter-text">{{ typedText }}</div>
  <div class="home-img col-lg-4">
    <img src="../../../assets/fotoProfilo.jpg" alt="">
  </div>
</div>
  <a class="arrow-wrap" href="#about">
    <div class="pulse">
      <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-chevron-down" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/>
      </svg>
    </div>
  </a>
</div>
