// myPortfolio/src/App.tsx

import './App.scss'
import About from './components/About'
import Home from './components/Home'
import Navbar from './components/Navbar'

function App() {

  return (
    <>
      <Navbar/>
      <main>
      <Home/>
      <About/>
      </main>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
      <p>ciao</p>
    </>
  )
}

export default App

// PortFolioAN/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'PortFolioAN';
}

<app-navbar></app-navbar>
<main>
  <app-home></app-home>
  <app-about></app-about>
  <app-card1></app-card1>
</main>
<router-outlet></router-outlet>
