// myPortfolio/src/components/Home.tsx
import imageName from "../assets/fotoProfilo.jpg";
import "./scss/Home.scss";
const Home = () => {
  return (
    <div className="home">
      <div className="home-img">
        <img src={imageName} alt="" />
      </div>
        <h2>
          Hi there, I'm <span className="V">Valerio</span>. A junior Web Developer passionate about <span className="C">coding</span> and digital design.
        </h2>
    </div>
  );
};

export default Home;

// PortFolioAN/src/app/Components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit{


  constructor() {}

  ngOnInit(): void {
  }

}

<div class="home">

  <h2>
    <span class="hover-text"></span>
    A junior Web Developer passionate about coding and digital design.
  </h2>
  <div class="home-img">
    <img src="../../../assets/fotoProfilo.jpg" alt="">
  </div>
</div>
