// myPortfolio/src/components/About.tsx
import "./scss/About.scss";

const About = () => {
  return (
    <div className="about">
      <div className="about_header">About</div>
      <p className="text">
        I am a 22-year-old guy, born in Rome. I have considered becoming a
        front-end developer after creating and managing a website using
        WordPress. This website sparked my passion for web app development.
      </p>
      <div className="about_header">Experience</div>
      <div>
        <h2 className="subtitle">Graduation</h2>
        <p className="text">
          Diploma in Automation obtained from Enrico Fermi Technical Institute
          in Rome.
        </p>
      </div>
      <div>
        <h2 className="subtitle">Professional course</h2>
        <p className="text">
          I attended a six-month course where I learned the fundamentals of
          Front-End and Back-End development. The last month of the course was
          dedicated to creating a website.
        </p>
      </div>
      <div>
        <h2 className="subtitle">Working</h2>
        <p className="text">
          I developed an e-commerce website using WordPress and a hosting
          platform for approximately six months. I also studied the basics of
          UX/UI and connected two companies through the website.{" "}
        </p>
      </div>
    </div>
  );
};

export default About;

// my-app/src/app/Components/about/about.component.ts
import { Component, HostListener, OnInit, Output, ElementRef } from '@angular/core';
@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styleUrls: ['./about.component.scss']
})
export class AboutComponent implements OnInit {
  altezzaDiv:number = 0;

  constructor(private elementRef: ElementRef) {}

  ngOnInit() {
  }
  /*@HostListener('window:scroll', ['$event'])
  nWindowScroll() {
  const myComponent = this.elementRef.nativeElement.querySelector('#about');
  this.altezzaDiv = myComponent.offsetTop;
  console.log(this.altezzaDiv)
}*/

}

<div class="spacing" id="about"></div>
<div class="about" >
  <div class="cont">

    <div class="about_header">About</div>
    <p class="text">
      I am a young and dynamic 22-year-old Junior Front End Developer, passionate about technology and with a fervent love for sports, cinema, and video games. My educational journey in Front End Development has provided me with a solid foundation of skills, but it's been my passion for sports since I was a child that has fueled my constant determination to achieve ambitious goals. My creativity and problem-solving approach have always been my strengths, while project organization allows me to maintain focus and productivity.
    </p>
    <div class="about_header">Experience</div>
    <div>
      <h2 class="subtitle">Graduation</h2>
      <p class="text">
        Diploma in Automation obtained from Enrico Fermi Technical Institute in
        Rome.
      </p>
    </div>
    <div>
      <h2 class="subtitle">Professional course</h2>
    <p class="text">
      I attended a six-month course where I learned the fundamentals of
      Front-End and Back-End development. The last month of the course was
      dedicated to creating a website.
    </p>
  </div>
  <div>
    <h2 class="subtitle">Working</h2>
    <p class="text work">
      I developed an e-commerce website using WordPress and a hosting platform
      for approximately six months. I also studied the basics of UX/UI and
      connected two companies through the website.
    </p>
  </div>
  <div class="wrap"></div>
</div>
</div>
