// PortFolioAN/src/app/Components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit{


  constructor() {}

  ngOnInit(): void {
  }

}

<div class="home">

  <h2>
    <span class="hover-text"></span>
    A junior Web Developer passionate about coding and digital design.
  </h2>
  <div class="home-img">
    <img src="../../../assets/fotoProfilo.jpg" alt="">
  </div>
</div>

// my-portfolio/src/components/Home.tsx
import imageName from "../assets/fotoProfilo.jpg";
const Home = () => {
  return (
    <div className="home">
      <h1>
        Hi there, I'm Valerio. A junior Web Developer passionate about coding
        and digital design.
      </h1>
      <div className="home-img">
        <img src={imageName} alt=""/>
      </div>
    </div>
  );
};

export default Home;
